### ISSUE TITLE
Private module attribute moved in Ansible Core 2.11

### ISSUE THREAD

**Issue by samdoran** [ansible-collections/cisco.iosxr#118]
##### SUMMARY

Argument spec validation has changed in Ansible Core 2.11. The following private attribute call should be changed to use the public variable:

```
cisco.iosxr/plugins/modules/iosxr_user.py
507:            type_checker = self._module._CHECK_ARGUMENT_TYPES_DISPATCHER[  # --> ansible.module_utils.common.parameters.DEFAULT_TYPE_VALIDATORS
```

The private attribute is available for backwards compatibility only.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`iosxr_user.py`

##### ANSIBLE VERSION

```paste below
2.11
```

**Comment by Qalthos** [comment]
We can't move to the new location while we support versions < 2.11, and the private attribute will persist for the foreseeable future.

I'm keeping the original issue at ansible-collections/ansible.netcommon#186 open for now to coordinate efforts around replacing it if and when that becomes feasible
