### ISSUE TITLE
iosxr_config broken (unexpected keyword arguments)

### ISSUE THREAD

**Issue by Thorbijoern** [ansible-collections/cisco.iosxr#161]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

https://github.com/ansible-collections/cisco.iosxr/blob/97a2136238955456ec4ac3385baab7c5b2b5c307/plugins/module_utils/network/iosxr/iosxr.py#L566

##### ANSIBLE VERSION

```paste below
ansible 2.10.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/tpentzien/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
```

I originally got the error with ansible 2.9, i just tried ansible 2.10 with collections hoping the error is gone.

##### COLLECTION VERSION

```paste below
cisco.iosxr 2.3.0
```

I originally got the error with ansible 2.9, i just tried ansible 2.10 with collections hoping the error is gone.

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

Ubuntu 18.04.5 LTS is the ansible host
Cisco IOS XE Software, Version 16.12.04 on WS-C3850-24T-E is the test switch

##### STEPS TO REPRODUCE

i've got some roles wich just roll out some jinja2 templates

```yaml
---
- name: logging
  iosxr_config:
    #save_when: always
    src: "{{ role_path }}/template.j2"
    #force: yes
  become: yes
```

##### EXPECTED RESULTS

the templates should get rolled out

##### ACTUAL RESULTS

the templates never get rolled out because the module runs into errors

```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_iosxr_config_payload_6AzgtQ/ansible_iosxr_config_payload.zip/ansible_collections/cisco/iosxr/plugins/module_utils/network/iosxr/iosxr.py", line 573, in load_config
    label=label,
  File "/tmp/ansible_iosxr_config_payload_6AzgtQ/ansible_iosxr_config_payload.zip/ansible/module_utils/connection.py", line 195, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [192.168.115.65]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "admin": false,
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "comment": "configured by iosxr_config",
            "config": null,
            "exclusive": false,
            "force": false,
            "label": null,
            "lines": null,
            "match": "line",
            "parents": null,
            "provider": null,
            "replace": "line",
            "src": "`..."
        }
    },
    "msg": "edit_config() got an unexpected keyword argument 'exclusive'"
}
```
(in the following only `msg` changes)

this is the first error i got, i searched in the sourcecode and found the problem: https://github.com/ansible-collections/cisco.iosxr/blob/97a2136238955456ec4ac3385baab7c5b2b5c307/plugins/module_utils/network/iosxr/iosxr.py#L566

first I commented `exclusive=exclusive,`, got error:

```
"msg": "edit_config() got an unexpected keyword argument 'admin'"
```

commended out `admin=admin,` too, got error:

```
"msg": "edit_config() got an unexpected keyword argument 'label'"
```

commented out `label=label,` too, final error:

```paste below
    "msg": "commit comment is not supported"
```
after then commenting out `comment=comment` it finaly worked like expected

that part of the code now looks like this:
```
response = conn.edit_config(
                candidate=command_filter,
                commit=commit,
                #admin=admin,
                #exclusive=exclusive,
                replace=replace,
                #comment=comment,
                #label=label,
            )
```

that works... i don't know if my dirty fix broke some other functionality of the collection but i also had the problem with ansible 2.9 where the module is still part of the main ansible distribution, but somehow other users don't seem to have that problem?

**Comment by ashwini-mhatre** [comment]
@Thorbijoern Could you please use https://github.com/ansible-collections/cisco.ios collection to configure XE devices? you are using wrong collection. This collection aims to configure iosxr boxes.

**Comment by ashwini-mhatre** [comment]
@Thorbijoern No issues :)
