### ISSUE TITLE
read-only user unable to run the "show version | utility head -n 20" in cliconf/iosxr.py

### ISSUE THREAD

**Issue by weixian17** [ansible-collections/cisco.iosxr#172]
##### SUMMARY

When read-only user tried to use show command module, always showing errors:
"msg": "show version | utility head -n 20\\r\\n\\r% This command is not authorized\\r\\nRP/0/RSP0/CPU0:Router#"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.iosxr.iosxr_facts
##### ANSIBLE VERSION

```paste below
ansible-playbook [core 2.12.0.dev0] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/share/ansible/collections/ansible_collections
Collection  Version
----------- -------
cisco.iosxr 2.4.0 
```

##### CONFIGURATION

```paste below
No output
```

##### OS / ENVIRONMENT

RP/0/RSP0/CPU0:Router#show version
Wed Aug 18 05:23:41.741 UTC

Cisco IOS XR Software, Version 6.0.1[Default]

##### STEPS TO REPRODUCE

IOS XR configured read-only user as below:
!Read-only user configured in IOS-XR router
username <>
 group read-only-tg
 secret 5 <>
!
service cli configuration disable usergroup read-only-tg

Running a playbook with iosxr_command always show error message: "msg": "show version | utility head -n 20\\r\\n\\r% This command is not authorized\\r\\nRP/0/RSP0/CPU0:Router#"
The issue is resolved after modifying the cliconf/iosxr.py "show version | utility head -n 20" to "show version"

```yaml
- name: cisco_sh_ver
  hosts: all
  gather_facts: false
  tasks:
  - name: show run on remote devices
    cisco.iosxr.iosxr_command:
     commands:
     - show run
     - show version
     - show inventory
    register: config
```

##### EXPECTED RESULTS

No error.

##### ACTUAL RESULTS

```paste below
The full traceback is:
  File "/tmp/ansible_cisco.iosxr.iosxr_command_payload_yc6_aecr/ansible_cisco.iosxr.iosxr_command_payload.zip/ansible_collections/cisco/iosxr/plugins/module_utils/network/iosxr/iosxr.py", line 179, in get_capabilities
    capabilities = Connection(module._socket_path).get_capabilities()
  File "/tmp/ansible_cisco.iosxr.iosxr_command_payload_yc6_aecr/ansible_cisco.iosxr.iosxr_command_payload.zip/ansible/module_utils/connection.py", line 195, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [Router]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "show version"
            ],
            "interval": 1,
            "match": "all",
            "provider": null,
            "retries": 10,
            "wait_for": null
        }
    },
    "msg": "show version | utility head -n 20\\r\\n\\r% This command is not authorized\\r\\nRP/0/RSP0/CPU0:Router#"
```

**Comment by ashwini-mhatre** [comment]
@weixian17 could you please try this same command on device.As on device also I am getting same error: **RP/0/0/CPU0:10#show version | utility head -n 20
% This command is not authorized
RP/0/0/CPU0:10#**

**Comment by weixian17** [comment]
@ashwini-mhatre Yes, I gotten the same error as you because the read only user has no rights to show this command with | utility. 
I modified the cliconf/iosxr.py to “show version” and issue resolved.
Thanks for looking into the issue.

**Comment by weixian17** [comment]
@ashwini-mhatre I would like to check is there any permanent fix for this issue? Or we have to manually change the iosxr.py everytime we using the new iosxr ansible-collection?
