### ISSUE TITLE
local variable 'start_index' referenced before assignment with cisco.iosxr.iosxr_config

### ISSUE THREAD

**Issue by aamsaleg** [ansible-collections/cisco.iosxr#191]
Ansible version: 2.9.13

Hello,

I'm trying to create this part of config:
extcommunity-set rt VRF1234
 6667:1234
end-set

to do this I perform:
   - name: Configure the extcommunity-set
      cisco.iosxr.iosxr_config:
        lines:
          - 6667:1234
          - end-set
        parents: extcommunity-set rt VRF1234

but it fails with this error: local variable 'start_index' referenced before assignment

The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/var/folders/wz/88zy3s2x13l_8lh478p6d3300000gn/T/ansible_cisco.iosxr.iosxr_config_payload_M6tYdA/ansible_cisco.iosxr.iosxr_config_payload.zip/ansible_collections/cisco/iosxr/plugins/modules/iosxr_config.py", line 355, in run
  File "/var/folders/wz/88zy3s2x13l_8lh478p6d3300000gn/T/ansible_cisco.iosxr.iosxr_config_payload_M6tYdA/ansible_cisco.iosxr.iosxr_config_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [asr9000v]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "admin": false,
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "comment": "configured by iosxr_config",
            "config": null,
            "exclusive": false,
            "force": false,
            "label": null,
            "lines": [
                "6667:1234",
                "end-set"
            ],
            "match": "line",
            "parents": [
                "extcommunity-set rt VRF1234"
            ],
            "provider": null,
            "replace": "line",
            "src": null
        }
    },
    "msg": "local variable 'start_index' referenced before assignment"

Because I use the same module to create some prefix-set (iosxr syntax is quite the same), I don't see what I'm missing for the extcommunity-set.

Kind regards;

**Comment by ashwini-mhatre** [comment]
https://github.com/ansible-collections/cisco.iosxr/pull/193 is merged for this issue
