### ISSUE TITLE
No default commit comment for IOSXR ansible network module

### ISSUE THREAD

**Issue by digitalfiend64** [ansible-collections/cisco.iosxr#198]
##### SUMMARY
No default commit comment for IOSXR ansible network module.

##### ISSUE TYPE
Unexpected default behavior of module.

##### COMPONENT NAME
cisco.iosxr

##### ADDITIONAL INFORMATION
The IOSXR ansible network module leaves a default commit comment if no comment is specified.  No other ansible modules used operates in this fashion.  Having no default commit comment created would bring the same uniform functionality that is observed in other ansible modules.

**Comment by ashwini-mhatre** [comment]
@digitalfiend64 
As par our current implementation of iosxr_config module, Iosxr_config is not designed to leave default label.But yes Iosxr_config leaves default comment when it pushes config to device. Could you please check this once again with customer?  
for more details please check model for iosxr_config. we have default value for comment option. but we don't have default value for label.
check line number 132 to 145
https://github.com/ansible-collections/cisco.iosxr/blob/main/plugins/modules/iosxr_config.py#L132

**Comment by ashwini-mhatre** [comment]
CC: @trishnaguha @digitalfiend64 
As par our last discussion I am assuming customer needs no default comment should leave while pushing config. I am updating same in description of the issue.

**Comment by ashwini-mhatre** [comment]
@digitalfiend64  we can target timeline for this issue as Feb 2022 release
