### ISSUE TITLE
Support IPv6 Ping

### ISSUE THREAD

**Issue by digitalfiend64** [ansible-collections/cisco.iosxr#228]
##### SUMMARY
Support IPv6 with ios_ping & nxos_ping

Build ping module for IOSXR (does not currently exist)

##### ISSUE TYPE
- Feature Idea, Feature Request

##### COMPONENT NAME
Cisco.iosxr.iosxr_ping

##### ADDITIONAL INFORMATION
Used to ping remote devices via module instead of using an xxxx_command module to send a raw command and having to parse and modify return data

(IPv6 support should be standard across all network modules)

**Comment by ashwini-mhatre** [comment]
@digitalfiend64 I think you need to create separate request in https://github.com/ansible-collections/cisco.nxos and https://github.com/ansible-collections/cisco.ios collection to support IPv6 with ios_ping & nxos_ping

**Comment by digitalfiend64** [comment]
> @digitalfiend64 I think you need to create separate request in https://github.com/ansible-collections/cisco.nxos and https://github.com/ansible-collections/cisco.ios collection to support IPv6 with ios_ping & nxos_ping

Other issues have been opened for netcommon and cisco.ios.

**Comment by digitalfiend64** [comment]
What's the latest on this?  Is there any ETA or timeframe of when this could be available to the customer in a GA release?

**Comment by KB-perByte** [comment]
Hey, @digitalfiend64 you may check this PR https://github.com/ansible-collections/cisco.iosxr/pull/240 we are planning to release it this month. 
Regards
