### ISSUE TITLE
Utilize the cisco.iosxr.iosxr_bgp_global module to create bgp neighbor-group and apply/inherit the neighbor-group to bgp neighbors in default and vrf contexts

### ISSUE THREAD

**Issue by digitalfiend64** [ansible-collections/cisco.iosxr#312]
#### SUMMARY

Utilize the cisco.iosxr.iosxr_bgp_global module to create bgp neighbor-group and apply/inherit the neighbor-group to bgp neighbors in default and vrf contexts.

##### ISSUE TYPE
- Feature Idea
Currently, these modules are built to add bgp neighbors in global and vrf contexts with required parameters but there is no way to create and apply the neighbor-groups(iosxr) or peer-templates (nxos) with these parameters. This feature is essential as most of our BGP configurations utilize the neighbor-group/peer-template configurations for repeatable and optimal configuration.

##### COMPONENT NAME

cisco.iosxr.iosxr_bgp_global

##### ADDITIONAL INFORMATION

This would help us avoid adding static templates for neighbor-group configurations and achieve comprehensive bgp configuration within the same module.

```yaml

router bgp {{ template['as_number'] }}
{% for neighbor in template['neighbors'] %}
{% if 'vrf' in neighbor %}
vrf {{ neighbor['vrf'] }}
{% endif %}
neighbor {{ neighbor['neighbor_address'] }}
  use neighbor-group {{ neighbor['neighbor_group'] }}
{% endfor %}


```

**Comment by ashwini-mhatre** [comment]
@digitalfiend64 As this feature idea will be across different networking collections(nxos,iosxr etc). we will discuss in the team next week and will get back by mid of the next week.
