### ISSUE TITLE
iosxr_interface:Integration test issue:Failed to commit one or more configuration items during a pseudo-atomic operation

### ISSUE THREAD

**Issue by komaldesai13** [ansible-collections/cisco.iosxr#350]
##### SUMMARY
When running ios_interface integration tests from Controller with EE container,
We get an unexpected error: Failed to commit one or more configuration items during a pseudo-atomic operation
On task [Populate configuration interface 0/0/0/0](https://github.com/ansible-collections/cisco.iosxr/blob/31a8aaecbb4eb8ba042e04acd22c77fdd8c10818/tests/integration/targets/iosxr_interfaces/tests/cli/_populate_config.yaml#L2)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.iosxr.iosxr_interface

##### ANSIBLE VERSION
2.14

##### COLLECTION VERSION
cisco.iosxr 4.0.3

##### CONFIGURATION
None

##### STEPS TO REPRODUCE
Run integration iosxr_interface test, the following task failed.
See below the actual results.

EXPECTED RESULTS

The task will pass with not errors.

ACTUAL RESULTS

TASK [/usr/share/ansible/collections/ansible_collections/cisco/iosxr/tests/integration/targets/iosxr_interfaces : Populate configuration interface 0/0/0/0] ***
task path: /usr/share/ansible/collections/ansible_collections/cisco/iosxr/tests/integration/targets/iosxr_interfaces/tests/cli/_populate_config.yaml:2
redirecting (type: terminal) ansible.builtin.iosxr to cisco.iosxr.iosxr
redirecting (type: cliconf) ansible.builtin.iosxr to cisco.iosxr.iosxr
The full traceback is:
  File "/usr/share/ansible/collections/ansible_collections/cisco/iosxr/plugins/module_utils/network/iosxr/iosxr.py", line 469, in load_config
    response = conn.edit_config(
  File "/usr/lib/python3.9/site-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [10.0.149.88]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "admin": false,
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "comment": "configured by iosxr_config",
            "config": null,
            "disable_default_comment": false,
            "exclusive": false,
            "force": false,
            "label": null,
            "lines": [
                "description this is interface0",
                "mtu 65",
                "speed 10",
                "no shutdown"
            ],
            "match": "line",
            "parents": [
                "interface GigabitEthernet 0/0/0/0"
            ],
            "replace": "line",
            "src": null
        }
    },
    "msg": "commit comment configured by iosxr_config\\r\\n\\r\\r\\n% Failed to commit one or more configuration items during a pseudo-atomic operation. All changes made have been reverted. Please issue 'show configuration failed [inheritance]' from this session to view the errors\\r\\nRP/0/RP0/CPU0:ios(config-if)#"
}

**Comment by ashwini-mhatre** [comment]
https://github.com/ansible-collections/cisco.iosxr/pull/347 merged
