### ISSUE TITLE
ansible ignore some lines on pushing prefix-set configuration 

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/cisco.iosxr#36]
_From @RehabRezek on Jun 10, 2020 09:19_

Hello,
i'm trying to push this prefix-set configuration on cisco ioxr with ansible 
```
prefix-set SWH22
  10.7.182.0/24,
  # EnodeB-S1-SADAT
  10.77.183.0/24,
  # EnodeB-S1-
  10.7.186.0/24,
  # EnodeB-S1-Bosh
  10.77.187.0/24,
  # test
  10.77.188.0/24
end-set
```
which are  ip and comment for each prefix-set 
but in every time ansible ignore the comment line and only ips are pushing to device 
any help if someone tried to push prefix-set before!?

_Copied from original issue: ansible/ansible#69980_

**Comment by RehabRezek** [comment]
@Qalthos Thanks for your reply 
as  i didn't use cliconf before, could you tell me what is the difference between cli_config and ios_config  when i push the configuration
i need to push it as  jinja file.

**Comment by rohitthakur2590** [comment]
resolved by https://github.com/ansible-collections/cisco.iosxr/pull/73
