### ISSUE TITLE
iosxr_config:Integration test issue:assertion failed

### ISSUE THREAD

**Issue by komaldesai13** [ansible-collections/cisco.iosxr#460]
##### SUMMARY
When running iosxr_config integration tests from Controller with EE container,
We get an unexpected error: Assertion failed
On task [Configure device with configuration](https://github.com/ansible-collections/cisco.iosxr/blob/main/tests/integration/targets/iosxr_config/tests/cli/backup.yaml#L13)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
iosxr_config

##### ANSIBLE VERSION
2.14

##### COLLECTION VERSION
cisco.iosxr 4.0.3

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE
Run integration iosxr_config  test, the following task failed.
See below the actual results.

##### EXPECTED RESULTS
The task will pass with not errors.

##### ACTUAL RESULTS

TASK [/usr/share/ansible/collections/ansible_collections/cisco/iosxr/tests/integration/targets/iosxr_config : Configure device with configuration] ***
01:13:06      task path: /usr/share/ansible/collections/ansible_collections/cisco/iosxr/tests/integration/targets/iosxr_config/tests/cli/backup.yaml:13
01:13:06      changed: [10.0.149.88] => {
01:13:06          "backup_path": "/usr/share/ansible/collections/ansible_collections/cisco/iosxr/tests/integration/targets/iosxr_config/backup/10.0.149.88_config.2023-11-27@19:42:53",
01:13:06          "changed": true,
01:13:06          "commands": [
01:13:06              "interface Loopback999",
01:13:06              "description this is a test",
01:13:06              "shutdown"
01:13:06          ],
01:13:06          "date": "2023-11-27",
01:13:06          "diff": {
01:13:06              "prepared": "Building configuration...\\n!! IOS XR Configuration 7.0.2\\n   interface Loopback999\\n+   description this is a test\\n+   shutdown\\n   !\\nend"
01:13:06          },
01:13:06          "filename": "10.0.149.88_config.2023-11-27@19:42:53",
01:13:06          "invocation": {
01:13:06              "module_args": {
01:13:06                  "admin": false,
01:13:06                  "after": null,
01:13:06                  "backup": true,
01:13:06                  "backup_options": null,
01:13:06                  "before": null,
01:13:06                  "comment": "configured by iosxr_config",
01:13:06                  "config": null,
01:13:06                  "disable_default_comment": false,
01:13:06                  "exclusive": false,
01:13:06                  "force": false,
01:13:06                  "label": null,
01:13:06                  "lines": null,
01:13:06                  "match": "line",
01:13:06                  "parents": null,
01:13:06                  "replace": "line",
01:13:06                  "src": "interface Loopback999\\n description this is a test\\n shutdown\\n"
01:13:06              }
01:13:06          },
01:13:06          "shortname": "/usr/share/ansible/collections/ansible_collections/cisco/iosxr/tests/integration/targets/iosxr_config/backup/10.0.149.88_config",
01:13:06          "time": "19:42:53",
01:13:06          "updates": [
01:13:06              "interface Loopback999",
01:13:06              "description this is a test",
01:13:06              "shutdown"
01:13:06          ]
01:13:06      }
01:13:06    
01:13:06      TASK [/usr/share/ansible/collections/ansible_collections/cisco/iosxr/tests/integration/targets/iosxr_config : ansible.builtin.assert] ***
01:13:06      task path: /usr/share/ansible/collections/ansible_collections/cisco/iosxr/tests/integration/targets/iosxr_config/tests/cli/backup.yaml:19
01:13:06      fatal: [10.0.149.88]: FAILED! => {
01:13:06          "assertion": "result.updates is not defined",
01:13:06          "changed": false,
01:13:06          "evaluated_to": false,
01:13:06          "msg": "Assertion failed"
01:13:06      }

**Comment by ashwini-mhatre** [comment]
fixed by https://github.com/ansible-collections/cisco.iosxr/pull/463
