### ISSUE TITLE
support for vrf module as nxos or ios collection

### ISSUE THREAD

**Issue by antoinekh** [ansible-collections/cisco.iosxr#462]
##### SUMMARY

Could it be possible to have a vrf module for the iosxr collection?
This module already exist for Cisco ios and nxos.

ios:
https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_vrf_module.html#ansible-collections-cisco-ios-ios-vrf-module

nxos:
https://docs.ansible.com/ansible/latest/collections/cisco/nxos/nxos_vrf_module.html#ansible-collections-cisco-nxos-nxos-vrf-module

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

We need at least something to know with interface is in which VRF with a gathered, and to be able to configure an interface in a specific VRF.

```yaml

```

**Comment by Ruchip16** [comment]
closing this issue, as we have merged [vrf_global](https://github.com/ansible-collections/cisco.iosxr/pull/467) and [vrf_address_family](https://github.com/ansible-collections/cisco.iosxr/pull/489) resource modules.
