### ISSUE TITLE
iosxr_banner module issue

### ISSUE THREAD

**Issue by sbanswar** [ansible-collections/cisco.iosxr#50]
The playbbok get timeout with multiple lines but if have only 2 lines it works, any pointer how to fix even I don't see option to increase timeout.
have tried both Login & Motd options

Ansible Version - 2.8.4 

name: Testing Cisco ASR9006
hosts: HOSTNAME
gather_facts: no
connection: netwotk_cli

tasks:

name: Configure the Login banner
iosxr_banner:
banner: login
text: |
line 1
line 2
line 3
state: present

**Comment by rohitthakur2590** [comment]
@sbanswar  could you try with latest release as It works fine, following are the examples to configure timers
```
export ANSIBLE_PERSISTENT_CONNECT_TIMEOUT=60
[persistent_connection]
command_timeout = 100
connect_timeout = 100
connect_retry_timeout = 100
```
https://docs.ansible.com/ansible/latest/reference_appendices/config.html

**Comment by sbanswar** [comment]
Hi Rohit,

What version are you suggesting , using 2.8.4? Tried with shared timers, still same error.

**Comment by sbanswar** [comment]
In addition, I don't think it's an issue with timeout, looks module doesn't able to understand the end of line hence throwing timeout error.
